### ISSUE TITLE
Converting Events(.txt file) back to images

### ISSUE THREAD

**Issue by BibratRanjan** [PIX2NVS/PIX2NVS#2]
How did you convert the events (.txt) file back to images of a video? I tried my own time quantization technique, it is giving a lot of null events.

Thanks

**Comment by PIX2NVS** [comment]
Solved the problems via email.

**Comment by 108mk** [comment]
[this question slightly deviate from the topic] Is there a way to visualise the converted *.txt file?
I mean as a neuromorphic event video.
The motivation is to know how well the (input) original  video get converted into the event stream (video).

Thanks, I find pix2nvs useful and interesting!!!
